// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: QT-Compassspj

#ifndef _QT_COMPASSSPJ_UI_H
#define _QT_COMPASSSPJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_selected;
extern lv_obj_t *ui_Roller_compass1;
extern lv_obj_t *ui_img_mask;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel_mask1;
extern lv_obj_t *ui_img_mask1;
extern lv_obj_t *ui_Image_selected1;
extern lv_obj_t *ui_Label_degree;
extern lv_obj_t *ui_Roller_compass3;
extern lv_obj_t *ui_Label_altitude;
extern lv_obj_t *ui_Label_degree1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_img_mask3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1854850271);   // assets/Images/selected-bg.png
LV_IMG_DECLARE( ui_img_images_mask_png);   // assets/Images/mask.png
LV_IMG_DECLARE( ui_img_images_altitude_png);   // assets/Images/altitude.png


LV_FONT_DECLARE( ui_font_B40);
LV_FONT_DECLARE( ui_font_R15);
LV_FONT_DECLARE( ui_font_R20);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
