// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: QT-Compassspj

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_mask1 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel_mask1, 100);
lv_obj_set_height( ui_Panel_mask1, 67);
lv_obj_set_align( ui_Panel_mask1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_mask1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_mask1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_mask1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_mask1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_mask1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_mask1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_mask1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_img_mask1, &ui_img_images_mask_png);
lv_obj_set_width( ui_img_mask1, LV_SIZE_CONTENT);  /// 129
lv_obj_set_height( ui_img_mask1, LV_SIZE_CONTENT);   /// 128
lv_obj_set_align( ui_img_mask1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mask1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mask1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_selected1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image_selected1, &ui_img_1854850271);
lv_obj_set_width( ui_Image_selected1, LV_SIZE_CONTENT);  /// 74
lv_obj_set_height( ui_Image_selected1, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_Image_selected1, -4 );
lv_obj_set_y( ui_Image_selected1, -1 );
lv_obj_set_align( ui_Image_selected1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_selected1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_selected1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image_selected1, lv_color_hex(0x600101), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image_selected1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_degree = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label_degree, 110);
lv_obj_set_height( ui_Label_degree, 51);
lv_obj_set_x( ui_Label_degree, -5 );
lv_obj_set_y( ui_Label_degree, 0 );
lv_obj_set_align( ui_Label_degree, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_degree,"360");
lv_obj_set_style_text_color(ui_Label_degree, lv_color_hex(0xF5FF02), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_degree, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_degree, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_degree, &ui_font_B40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_compass3 = lv_roller_create(ui_Screen2);
lv_roller_set_options( ui_Roller_compass3, "N\nNE\nE\nSE\nS\nSW\nW\nNW", LV_ROLLER_MODE_INFINITE );
lv_roller_set_selected( ui_Roller_compass3, 2, LV_ANIM_OFF);
lv_obj_set_width( ui_Roller_compass3, 99);
lv_obj_set_height( ui_Roller_compass3, 24);
lv_obj_set_x( ui_Roller_compass3, 5 );
lv_obj_set_y( ui_Roller_compass3, 46 );
lv_obj_set_align( ui_Roller_compass3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Roller_compass3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_Roller_compass3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_compass3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_compass3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_compass3, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_compass3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller_compass3, &ui_font_R20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_compass3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_compass3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_compass3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_compass3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Roller_compass3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_compass3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_compass3, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_compass3, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_compass3, 5, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_compass3, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller_compass3, &ui_font_R20, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_compass3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_compass3, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label_altitude = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label_altitude, 69);
lv_obj_set_height( ui_Label_altitude, 16);
lv_obj_set_x( ui_Label_altitude, -2 );
lv_obj_set_y( ui_Label_altitude, -45 );
lv_obj_set_align( ui_Label_altitude, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_altitude,"15000 m");
lv_obj_set_style_text_color(ui_Label_altitude, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_altitude, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_altitude, &ui_font_R15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_degree1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label_degree1, 20);
lv_obj_set_height( ui_Label_degree1, 17);
lv_obj_set_x( ui_Label_degree1, 50 );
lv_obj_set_y( ui_Label_degree1, -31 );
lv_obj_set_align( ui_Label_degree1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_degree1,"°");
lv_obj_set_style_text_color(ui_Label_degree1, lv_color_hex(0xF5FF02), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_degree1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_degree1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_degree1, &ui_font_R20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image1, &ui_img_images_altitude_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Image1, 41 );
lv_obj_set_y( ui_Image1, -45 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_transform_angle(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_mask3 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_img_mask3, &ui_img_images_mask_png);
lv_obj_set_width( ui_img_mask3, LV_SIZE_CONTENT);  /// 129
lv_obj_set_height( ui_img_mask3, LV_SIZE_CONTENT);   /// 128
lv_obj_set_align( ui_img_mask3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mask3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mask3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
