// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: QT-Compassspj

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_selected = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_selected, &ui_img_1854850271);
lv_obj_set_width( ui_Image_selected, LV_SIZE_CONTENT);  /// 74
lv_obj_set_height( ui_Image_selected, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_Image_selected, -4 );
lv_obj_set_y( ui_Image_selected, -1 );
lv_obj_set_align( ui_Image_selected, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_selected, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_selected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image_selected, lv_color_hex(0x600101), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image_selected, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_compass1 = lv_roller_create(ui_Screen1);
lv_roller_set_options( ui_Roller_compass1, "N\nNE\nE\nSE\nS\nSW\nW\nNW", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_Roller_compass1, 103);
lv_obj_set_height( ui_Roller_compass1, 130);
lv_obj_set_x( ui_Roller_compass1, -3 );
lv_obj_set_y( ui_Roller_compass1, 0 );
lv_obj_set_align( ui_Roller_compass1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Roller_compass1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_Roller_compass1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_compass1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_compass1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_compass1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_compass1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller_compass1, &ui_font_R20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_compass1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_compass1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_compass1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_compass1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Roller_compass1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_compass1, lv_color_hex(0xF5FF02), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_compass1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_compass1, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller_compass1, &ui_font_B40, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_compass1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_compass1, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_img_mask = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_mask, &ui_img_images_mask_png);
lv_obj_set_width( ui_img_mask, LV_SIZE_CONTENT);  /// 129
lv_obj_set_height( ui_img_mask, LV_SIZE_CONTENT);   /// 128
lv_obj_set_align( ui_img_mask, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mask, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
